[colors]
cursor = { cursor='#626880', text = '#c6d0f5' }
selection={ background = '#626880', text = '#c6d0f5' }
vi_mode_cursor={ cursor = '#626880', text = '#c6d0f5' }

[colors.search]
focused_match = {background = "#ff6a19",foreground = "#ffffff"}
matches = {background = "#626880",foreground = "#ffffff"}

[colors.primary]
background = '#303446'
foreground = '#c6d0f5'

[colors.bright]
black = '#626880'
blue = '#7b9ef0'
cyan = '#5abfb5'
green = '#8ec772'
magenta = '#f2a4db'
red = '#e67172'
white = '#b5bfe2'
yellow = '#d9ba73'

[colors.normal]
black = '#51576d'
blue = '#8caaee'
cyan = '#81c8be'
green = '#a6d189'
magenta = '#f4b8e4'
red = '#e78284'
white = '#a5adce'
yellow = '#e5c890'


[font]
  normal={family= "SauceCodePro Nerd Font Mono",style=  "Regular"}
  italic={family= "SauceCodePro Nerd Font Mono",style=  "Italic"}
  bold=  {family="SauceCodePro Nerd Font Mono",style=  "Bold"}
  bold_italic={family= "SauceCodePro Nerd Font Mono",style=  "Bold Italic"}
  offset = {x=0,y=0}
  glyph_offset= {x=0,y=0}
  builtin_box_drawing = false
  size=20

[window]
  dimensions ={columns=80,lines=24}
  dynamic_title = false
  title = "Alacritty"
  padding = { x = 0, y = 0}
  dynamic_padding=false
  opacity = 1

[scrolling]
   history = 2000
   multiplier = 5

[keyboard]
bindings=[
{ key="c", mods="Alt",action="Copy"},
{ key="v", mods="Alt",action="Paste"},
{ key="c", mods="Shift|Control",action="Copy"},
{ key="v", mods="Shift|Control",action="Paste"},

{ key="a", mods="Shift|Alt",action="IncreaseFontSize"},
{ key="z", mods="Shift|Alt",action="DecreaseFontSize"},
{ key="r", mods="Shift|Alt",action="ResetFontSize"},

{ key="u", mods="Shift|Alt", action="ScrollLineUp"},
{ key="d", mods="Shift|Alt", action="ScrollLineDown"},
{ key="u", mods="Shift|Control",action="ScrollPageUp"},
{ key="d", mods="Shift|Control", action="ScrollPageDown"},

{ key="g", mods="Shift|Alt", action="ToggleViMode"},
{ key="f", mods="Shift|Alt", action="SearchForward"},
{ key="b", mods="Shift|Alt", action="SearchBackward"},
# { key="s", mods="Alt", chars = "\u003A\u0077\u0071\u000D"},
]

[mouse]
hide_when_typing = true

#[shell]
#program = "wsl.exe"
#args=["--cd","~","--exec","tmux", "attach-session", "-t", "home"]

[env]
TERM="xterm-256color"
